name: cpplint
on: [push, pull_request]
jobs:
  cpplint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-python@v1
    - run: pip install cpplint
    - run: find . -type f -name "*.cpp" | xargs cpplint --recursive
    - run: find . -type f -name "*.h" | xargs cpplint --recursive

  pythonPylintGithubAction:
    name: Python Pylint Github Action
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Python Pylint Github Action
      uses: fylein/python-pylint-github-action@master
      with:
        args: find . -type f -name "*.py" | xargs pylint

  pyrecheck:
   name : Pyre Check Github Action
   runs-on: ubuntu-latest
   steps:
   - uses: actions/checkout@v2
   - uses: actions/setup-python@v1
   - run: brew install watchman
   - run: pip install pyre-check
   - run: pyre init 
   - run: pyre
