name: cpplint
on: [push, pull_request]
jobs:
  cpplint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-python@v1
    - run: pip install cpplint
    - run: pwd
    - run: cpplint --recursive

  pythonPylintGithubAction:
    name: Python Pylint Github Action
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Python Pylint Github Action
      uses: fylein/python-pylint-github-action@master
      with:
        args: find . -type f -name "*.py" | xargs pylint

  pyrecheck:
   name : Pyre Check Github Action
   runs-on: ubuntu-latest
   steps:
   - uses: actions/checkout@v2
   - name: Set up Python 3.x
     uses: actions/setup-python@v1
     with:
        python-version: '3.x'
   - name: Pyre-Check Action Step
     uses: lissahyacinth/pyre-check-action@v1.1.3
     with:
        token: ${{ secrets.GITHUB_TOKEN }}
        pip: "numpy pandas"
        args: "--source-directory ."
