name: cpplint
on: [push, pull_request]
jobs:
  cpplint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-python@v1
    - run: pip install cpplint
    - run: cpplint --help

  pythonPylintGithubAction:
    name: Python Pylint Github Action
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Python Pylint Github Action
      uses: fylein/python-pylint-github-action@master
      with:
        args: pylint --help